;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2019/1/11 10:01:52

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1000=什么是图形编辑器.html	; 什么是图形编辑器
IDH_1002=文件操作.html	; 文件操作
IDH_1003=绘制图形.html	; 绘制图形
IDH_1004=图层操作.html	; 图层操作
IDH_1005=插入图文.html	; 插入图文
IDH_1006=图形移动.html	; 图形移动
IDH_1007=关于.html	; 关于
