;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2019/1/11 10:01:52

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1000	1000	; 什么是图形编辑器 什么是图形编辑器.html
#define IDH_1002	1002	; 文件操作 文件操作.html
#define IDH_1003	1003	; 绘制图形 绘制图形.html
#define IDH_1004	1004	; 图层操作 图层操作.html
#define IDH_1005	1005	; 插入图文 插入图文.html
#define IDH_1006	1006	; 图形移动 图形移动.html
#define IDH_1007	1007	; 关于 关于.html
